appName: ussd-bankerbet-platform
namespace: ussd-platform
replicaCount: 1

image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable"

      # repository: europe-west3-docker.pkg.dev/betika-shared-services/ussd-platform/ussd-bankerbet-platform
      # pullPolicy: IfNotPresent
      # tag: "latest"

podAnnotations: {}

configMap:
  name: ussd-bankerbet-platform-config
    
enVars:
  data:
        GRPC_PORT: "8040"
        SERVER_PORT: "8080"
        APP: "banker_bet"
        LOG_LEVEL: "DEBUG"
        READ_DB: "dev-mysql01_user:4c5cKAeMvx6N58b%PuyfH7MbSak4MQ7cD@tcp(dev-mysql01-primary.betika.private:3306)/dev_betika?parseTime=true&timeout=5s"
        WRITE_DB: "dev-mysql01_user:4c5cKAeMvx6N58b%PuyfH7MbSak4MQ7cD@tcp(dev-mysql01-primary.betika.private:3306)/dev_betika?parseTime=true&timeout=5s"
        NOTIFICATION_API_URL: "http://dev-appserver01-node01.betika.private:13004/consume"
        NOTIFICATION_CLIENT_ID: "INSOMNIA"
        NOTIFICATION_CLIENT_SECRET: "C5wfZ8GthVKpGt9PgGdpbJFe9ttmYxTY"
        hpa: "ussd-bsnkerbet-platform-hpa"
        WHITELIST_IPS: ""
        WEB_API: "https://api-cd.betika.com"
        WALLET_URL: "dev-ke-wallet-account.betika.private:8040"
        API_REQUEST_TIMEOUT: "3"   

service:
  http:
    enabled: true
    name: ussd-bankerbet-platform-svc
    type: ClusterIP
    port: 8080
    targetPort: 8080
    containerPort: 8080 
    
  grpc:
      enabled: true
      name: ussd-bankerbet-platform-svc-grpc
      type: ClusterIP
      port: 8040
      targetPort: 8040
      containerPort: 8040

livenessProbe:
  httpGet:
      path: /
      port: http
readinessProbe:
  httpGet:
      path: /
      port: http
# Resource Limits (Prevent excessive resource consumption)
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 512Mi
    
autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 80




  