appName: ussd-client-platform
namespace: ussd-platform
replicaCount: 1

image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable"

      # repository: europe-west3-docker.pkg.dev/betika-shared-services/ussd-platform/ussd-client-platform
      # pullPolicy: IfNotPresent
      # tag: "latest"

podAnnotations: {}

configMap:
  name: ussd-airtel-ug-proxy-config
    
enVars:
  data:
        CLIENT_HOST_ADDR: "devel-ug-ussd-client-service.betika.private:8040"
        ACCOUNT_HOST_ADDR: "devel-ug-ussd-account-service.betika.private:8040"
        GRPC_SERVER: "8040"
        GATEWAY_PORT: "8080"
        APP: "Airtel UG Proxy"
        KAFKA_BROKER: "pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
        KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
        KAFKA_SASL_MECHANISM: "PLAIN"
        KAFKA_CLUSTER_API_KEY: "MVIPTC5AHSSBJUX3"
        KAFKA_CLUSTER_API_SECRET: "h0ttsyWSOk6BMY1cc+8NhnKmtciU+6M+aNQ5ZXlZjLhSkVts5yjoToUFNW06n6MX"
        KAFKA_SCHEMA_REGISTRY: "https://psrc-yo2rpj.europe-southwest1.gcp.confluent.cloud"
        KAFKA_SCHEMA_REGISTRY_API_KEY: "TQSJPC3RCBHWORU7"
        KAFKA_SCHEMA_REGISTRY_API_SECRET: "DH7Z3bgGvWoVL2InMbM0i/L2A/hO4pVvVgOb9NacwH7pq4GhJH8X5IvTRZQYuznf"
        LOG_LEVEL: ""
        CP_REF_ID: "193"
        CLIENT_REQUESTS_TIMEOUT: "10"   

service:
  http:
    enabled: true
    name: ussd-ug-client-platform-svc
    type: ClusterIP
    port: 8080
    targetPort: 8080
    containerPort: 8080 
    
  grpc:
      enabled: true
      name: ussd-ug-client-platform-svc-grpc
      type: ClusterIP
      port: 8040
      targetPort: 8040
      containerPort: 8040

livenessProbe:
  httpGet:
      path: /
      port: http
readinessProbe:
  httpGet:
      path: /
      port: http

autoscaling:
  enabled: false



  