appName: ussd-payments-platform
namespace: ussd-platform
replicaCount: 1

image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "stable"

      # repository: europe-west3-docker.pkg.dev/betika-shared-services/ussd-platform/ussd-payments-platform
      # pullPolicy: IfNotPresent
      # tag: "latest"

podAnnotations: {}

configMap:
  name: ussd-payments-platform-config
    
enVars:
  data:
        GRPC_HOST_PORT: "8040"
        HTTP_HOST_PORT: "8080"
        REDIS_READ_HOST: "127.0.0.1"
        REDIS_READ_PORT: "7001"
        REDIS_READ_PASSWORD: ""
        REDIS_WRITE_HOST: "127.0.0.1"
        REDIS_WRITE_PORT: "7001"
        REDIS_WRITE_PASSWORD: ""
        REDIS_DB: "0"
        WALLET_API_URL: "https://dev-fn-core-ussd-api-mtnm4zmsra-ey.a.run.app/ussd"
        WALLET_HEADER_ACCESS_TOKEN: "d6bb95a7-d1f3-4b98-90a0-154770049736"
        MINIMUM_WITHDRAWAL_AMOUNT: "1000"
        MAXIMUM_WITHDRAWAL_AMOUNT: "5000000"
        ACCOUNT_HOST: "devel-ug-ussd-account-service.betika.private:8040"
        LOG_LEVEL: "debug"
        APP: "payments"
        MINIMUM_DEPOSIT_AMOUNT: "1000"
        MAXIMUM_DEPOSIT_AMOUNT: "5000000"
        COUNTRY: "UG"
        MTN_PROVIDER_ID: "8"
        AIRTEL_PROVIDER_ID: "9"
        KAFKA_BROKER: "pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
        KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
        KAFKA_SASL_MECHANISM: "PLAIN"
        KAFKA_CLUSTER_API_KEY: "MVIPTC5AHSSBJUX3"
        KAFKA_CLUSTER_API_SECRET: "h0ttsyWSOk6BMY1cc+8NhnKmtciU+6M+aNQ5ZXlZjLhSkVts5yjoToUFNW06n6MX"
        KAFKA_SCHEMA_REGISTRY: "https://psrc-yo2rpj.europe-southwest1.gcp.confluent.cloud"
        KAFKA_SCHEMA_REGISTRY_API_KEY: "TQSJPC3RCBHWORU7"
        KAFKA_SCHEMA_REGISTRY_API_SECRET: "DH7Z3bgGvWoVL2InMbM0i/L2A/hO4pVvVgOb9NacwH7pq4GhJH8X5IvTRZQYuznf"
        INIT_KAFKA: "true"
        RESUME_SESSION: "false"
        API_REQUEST_TIMEOUT: "3"
        API_AUTH_TOKEN_REQUEST_TIMEOUT: "5"
        APP_ENV: "development"   

service:
  http:
    enabled: true
    name: ussd-ug-payments-platform-svc
    type: ClusterIP
    port: 8080
    targetPort: 8080
    
  grpc:
      enabled: true
      name: ussd-ug-payments-platform-svc-grpc
      type: ClusterIP
      port: 8040
      targetPort: 8040

livenessProbe:
  httpGet:
      path: /
      port: http
readinessProbe:
  httpGet:
      path: /
      port: http

autoscaling:
  enabled: false



  