{{- if .Values.service.http.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.http.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ussd-platform.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.http.type }} 
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
{{- end }}