apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ussd
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: devel
                  server: https://kubernetes.default.svc
          - list:
              elements:
                - name: payments
                  # repoPath: helm-chart/betika-devel/payments/values.yaml
                  namespace: ussd-platform
                - name: client
                  # repoPath: helm-chart/betika-devel/client/values.yaml
                  namespace: ussd-platform 
                - name: account
                  # repoPath: helm-chart/betika-devel/client/values.yaml
                  namespace: ussd-platform  
                - name: sport
                  # repoPath: helm-chart/betika-devel/client/values.yaml
                  namespace: ussd-platform  
                - name: bankerbet
                  # repoPath: helm-chart/betika-devel/client/values.yaml
                  namespace: ussd-platform         
  template:
    metadata:
      name: "{{name}}-{{environment}}"
    spec:
      project: ussd
      source:
        repoURL: https://github.com/Providence-ops/ussd-platform.git
        path: helm-chart
        targetRevision: HEAD
        helm:
          valueFiles:
            - betika-devel/{{name}}/values.yaml 
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true